add_newline = false

[character]
# success_symbol = "[âœ ](bold green)"
error_symbol = "[âœ—](bold red)"

[gcloud]
disabled=true

[kotlin]
disabled = true
symbol = "ğŸ…º "

[kubernetes]
disabled=true

[aws]
disabled=true
symbol = "îŒ½ "

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[conda]
symbol = "ï„Œ "

[docker_context]
symbol = "ïŒˆ "

[golang]
symbol = "î˜§ "

[java]
symbol = "î‰– "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ï€“ "

[custom.direnv]
symbol = "î€ "
when = """ test -n "$DIRENV_DIR" """

[custom.work]
# symbol = "ï™¨ "
# symbol = "ï„“ "
command = " test $GITHUB_TOKEN = $TES_GITHUB_API_TOKEN && echo Tes || echo JL"
when = """ test -n "$GITHUB_TOKEN" """
style = "blue"
format = "[$symbol($output)]($style) "

[git_status]
## temporary workaround for: https://github.com/kovidgoyal/kitty/issues/5026
# style = "red"
# ahead = "ïƒ"
# behind = "ïƒ"
# diverged = "ïƒœ"

[custom.ls_level]
command = "echo $LF_LEVEL"
when = """ test -n "$LF_LEVEL" """
style = "fg:purple"
format = "[(LF@$output)]($style)"
